// Code generated by github.com/varlink/go/cmd/varlink-go-interface-generator, DO NOT EDIT.

package devatteztagent

import (
	"context"
	"github.com/varlink/go/varlink"
)

// Generated type declarations

type Status struct {
	Ek                string `json:"ek"`
	Enrolled          bool   `json:"enrolled"`
	AcmeServer        string `json:"acmeServer"`
	AttestationServer string `json:"attestationServer"`
}

type CertificateChain struct {
	Device       string `json:"device"`
	Intermediate string `json:"intermediate"`
}

func Dispatch_Error(err error) error {
	if e, ok := err.(*varlink.Error); ok {
		switch e.Name {
		}
	}
	return err
}

// Generated client method calls

type GetStatus_methods struct{}

func GetStatus() GetStatus_methods { return GetStatus_methods{} }

func (m GetStatus_methods) Call(ctx context.Context, c *varlink.Connection) (status_out_ Status, err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	status_out_, _, err_ = receive(ctx)
	return
}

func (m GetStatus_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) (Status, uint64, error), error) {
	receive, err := c.Send(ctx, "dev.attezt.Agent.GetStatus", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (status_out_ Status, flags uint64, err error) {
		var out struct {
			Status Status `json:"status"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		status_out_ = out.Status
		return
	}, nil
}

func (m GetStatus_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (status_out_ Status, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "dev.attezt.Agent.GetStatus", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (status_out_ Status, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Status Status `json:"status"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		status_out_ = out.Status
		return
	}, nil
}

type EnrollDevice_methods struct{}

func EnrollDevice() EnrollDevice_methods { return EnrollDevice_methods{} }

func (m EnrollDevice_methods) Call(ctx context.Context, c *varlink.Connection) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m EnrollDevice_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) (uint64, error), error) {
	receive, err := c.Send(ctx, "dev.attezt.Agent.EnrollDevice", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m EnrollDevice_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "dev.attezt.Agent.EnrollDevice", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type GetCertificate_methods struct{}

func GetCertificate() GetCertificate_methods { return GetCertificate_methods{} }

func (m GetCertificate_methods) Call(ctx context.Context, c *varlink.Connection) (chain_out_ CertificateChain, err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	chain_out_, _, err_ = receive(ctx)
	return
}

func (m GetCertificate_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) (CertificateChain, uint64, error), error) {
	receive, err := c.Send(ctx, "dev.attezt.Agent.GetCertificate", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (chain_out_ CertificateChain, flags uint64, err error) {
		var out struct {
			Chain CertificateChain `json:"chain"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		chain_out_ = out.Chain
		return
	}, nil
}

func (m GetCertificate_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (chain_out_ CertificateChain, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "dev.attezt.Agent.GetCertificate", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (chain_out_ CertificateChain, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Chain CertificateChain `json:"chain"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		chain_out_ = out.Chain
		return
	}, nil
}

type RenewCertificate_methods struct{}

func RenewCertificate() RenewCertificate_methods { return RenewCertificate_methods{} }

func (m RenewCertificate_methods) Call(ctx context.Context, c *varlink.Connection) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m RenewCertificate_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) (uint64, error), error) {
	receive, err := c.Send(ctx, "dev.attezt.Agent.RenewCertificate", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m RenewCertificate_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "dev.attezt.Agent.RenewCertificate", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

// Generated service interface with all methods

type devatteztagentInterface interface {
	GetStatus(ctx context.Context, c VarlinkCall) error
	EnrollDevice(ctx context.Context, c VarlinkCall) error
	GetCertificate(ctx context.Context, c VarlinkCall) error
	RenewCertificate(ctx context.Context, c VarlinkCall) error
}

// Generated service object with all methods

type VarlinkCall struct{ varlink.Call }

// Generated reply methods for all varlink errors

// Generated reply methods for all varlink methods

func (c *VarlinkCall) ReplyGetStatus(ctx context.Context, status_ Status) error {
	var out struct {
		Status Status `json:"status"`
	}
	out.Status = status_
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyEnrollDevice(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyGetCertificate(ctx context.Context, chain_ CertificateChain) error {
	var out struct {
		Chain CertificateChain `json:"chain"`
	}
	out.Chain = chain_
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyRenewCertificate(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

// Generated dummy implementations for all varlink methods

func (s *VarlinkInterface) GetStatus(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "dev.attezt.Agent.GetStatus")
}

func (s *VarlinkInterface) EnrollDevice(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "dev.attezt.Agent.EnrollDevice")
}

func (s *VarlinkInterface) GetCertificate(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "dev.attezt.Agent.GetCertificate")
}

func (s *VarlinkInterface) RenewCertificate(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "dev.attezt.Agent.RenewCertificate")
}

// Generated method call dispatcher

func (s *VarlinkInterface) VarlinkDispatch(ctx context.Context, call varlink.Call, methodname string) error {
	switch methodname {
	case "GetStatus":
		return s.devatteztagentInterface.GetStatus(ctx, VarlinkCall{call})

	case "EnrollDevice":
		return s.devatteztagentInterface.EnrollDevice(ctx, VarlinkCall{call})

	case "GetCertificate":
		return s.devatteztagentInterface.GetCertificate(ctx, VarlinkCall{call})

	case "RenewCertificate":
		return s.devatteztagentInterface.RenewCertificate(ctx, VarlinkCall{call})

	default:
		return call.ReplyMethodNotFound(ctx, methodname)
	}
}

// Generated varlink interface name

func (s *VarlinkInterface) VarlinkGetName() string {
	return `dev.attezt.Agent`
}

// Generated varlink interface description

func (s *VarlinkInterface) VarlinkGetDescription() string {
	return `interface dev.attezt.Agent

type Status (
  ek: string,
  enrolled: bool,
  acmeServer: string,
  attestationServer: string
)

type CertificateChain (
  device: string,
  intermediate: string
) 

method GetStatus() -> (status: Status)
method EnrollDevice() -> ()
method GetCertificate() -> (chain: CertificateChain)
method RenewCertificate() -> ()
`
}

// Generated service interface

type VarlinkInterface struct {
	devatteztagentInterface
}

func VarlinkNew(m devatteztagentInterface) *VarlinkInterface {
	return &VarlinkInterface{m}
}
