// Code generated by github.com/varlink/go/cmd/varlink-go-interface-generator, DO NOT EDIT.

package devattezt

import (
	"context"
	"github.com/varlink/go/varlink"
)

// Generated type declarations

type Device struct {
	Ekcert string `json:"ekcert"`
}

func Dispatch_Error(err error) error {
	if e, ok := err.(*varlink.Error); ok {
		switch e.Name {
		}
	}
	return err
}

// Generated client method calls

type GetDevice_methods struct{}

func GetDevice() GetDevice_methods { return GetDevice_methods{} }

func (m GetDevice_methods) Call(ctx context.Context, c *varlink.Connection, ekcert_in_ string) (device_out_ Device, err_ error) {
	receive, err_ := m.Send(ctx, c, 0, ekcert_in_)
	if err_ != nil {
		return
	}
	device_out_, _, err_ = receive(ctx)
	return
}

func (m GetDevice_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, ekcert_in_ string) (func(ctx context.Context) (Device, uint64, error), error) {
	var in struct {
		Ekcert string `json:"ekcert"`
	}
	in.Ekcert = ekcert_in_
	receive, err := c.Send(ctx, "dev.attezt.GetDevice", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (device_out_ Device, flags uint64, err error) {
		var out struct {
			Device Device `json:"device"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		device_out_ = out.Device
		return
	}, nil
}

func (m GetDevice_methods) Upgrade(ctx context.Context, c *varlink.Connection, ekcert_in_ string) (func(ctx context.Context) (device_out_ Device, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Ekcert string `json:"ekcert"`
	}
	in.Ekcert = ekcert_in_
	receive, err := c.Upgrade(ctx, "dev.attezt.GetDevice", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (device_out_ Device, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Device Device `json:"device"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		device_out_ = out.Device
		return
	}, nil
}

type ListDevices_methods struct{}

func ListDevices() ListDevices_methods { return ListDevices_methods{} }

func (m ListDevices_methods) Call(ctx context.Context, c *varlink.Connection) (devices_out_ []Device, err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	devices_out_, _, err_ = receive(ctx)
	return
}

func (m ListDevices_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) ([]Device, uint64, error), error) {
	receive, err := c.Send(ctx, "dev.attezt.ListDevices", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (devices_out_ []Device, flags uint64, err error) {
		var out struct {
			Devices []Device `json:"devices"`
		}
		flags, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		devices_out_ = []Device(out.Devices)
		return
	}, nil
}

func (m ListDevices_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (devices_out_ []Device, flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "dev.attezt.ListDevices", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (devices_out_ []Device, flags uint64, conn varlink.ReadWriterContext, err error) {
		var out struct {
			Devices []Device `json:"devices"`
		}
		flags, conn, err = receive(ctx, &out)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		devices_out_ = []Device(out.Devices)
		return
	}, nil
}

type Enroll_methods struct{}

func Enroll() Enroll_methods { return Enroll_methods{} }

func (m Enroll_methods) Call(ctx context.Context, c *varlink.Connection, ekcert_in_ string) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, ekcert_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m Enroll_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, ekcert_in_ string) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Ekcert string `json:"ekcert"`
	}
	in.Ekcert = ekcert_in_
	receive, err := c.Send(ctx, "dev.attezt.Enroll", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m Enroll_methods) Upgrade(ctx context.Context, c *varlink.Connection, ekcert_in_ string) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Ekcert string `json:"ekcert"`
	}
	in.Ekcert = ekcert_in_
	receive, err := c.Upgrade(ctx, "dev.attezt.Enroll", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

type Remove_methods struct{}

func Remove() Remove_methods { return Remove_methods{} }

func (m Remove_methods) Call(ctx context.Context, c *varlink.Connection, ekcert_in_ string) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, ekcert_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m Remove_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, ekcert_in_ string) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Ekcert string `json:"ekcert"`
	}
	in.Ekcert = ekcert_in_
	receive, err := c.Send(ctx, "dev.attezt.Remove", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m Remove_methods) Upgrade(ctx context.Context, c *varlink.Connection, ekcert_in_ string) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Ekcert string `json:"ekcert"`
	}
	in.Ekcert = ekcert_in_
	receive, err := c.Upgrade(ctx, "dev.attezt.Remove", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

// Generated service interface with all methods

type devatteztInterface interface {
	GetDevice(ctx context.Context, c VarlinkCall, ekcert_ string) error
	ListDevices(ctx context.Context, c VarlinkCall) error
	Enroll(ctx context.Context, c VarlinkCall, ekcert_ string) error
	Remove(ctx context.Context, c VarlinkCall, ekcert_ string) error
}

// Generated service object with all methods

type VarlinkCall struct{ varlink.Call }

// Generated reply methods for all varlink errors

// Generated reply methods for all varlink methods

func (c *VarlinkCall) ReplyGetDevice(ctx context.Context, device_ Device) error {
	var out struct {
		Device Device `json:"device"`
	}
	out.Device = device_
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyListDevices(ctx context.Context, devices_ []Device) error {
	var out struct {
		Devices []Device `json:"devices"`
	}
	out.Devices = []Device(devices_)
	return c.Reply(ctx, &out)
}

func (c *VarlinkCall) ReplyEnroll(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyRemove(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

// Generated dummy implementations for all varlink methods

func (s *VarlinkInterface) GetDevice(ctx context.Context, c VarlinkCall, ekcert_ string) error {
	return c.ReplyMethodNotImplemented(ctx, "dev.attezt.GetDevice")
}

func (s *VarlinkInterface) ListDevices(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "dev.attezt.ListDevices")
}

func (s *VarlinkInterface) Enroll(ctx context.Context, c VarlinkCall, ekcert_ string) error {
	return c.ReplyMethodNotImplemented(ctx, "dev.attezt.Enroll")
}

func (s *VarlinkInterface) Remove(ctx context.Context, c VarlinkCall, ekcert_ string) error {
	return c.ReplyMethodNotImplemented(ctx, "dev.attezt.Remove")
}

// Generated method call dispatcher

func (s *VarlinkInterface) VarlinkDispatch(ctx context.Context, call varlink.Call, methodname string) error {
	switch methodname {
	case "GetDevice":
		var in struct {
			Ekcert string `json:"ekcert"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.devatteztInterface.GetDevice(ctx, VarlinkCall{call}, in.Ekcert)

	case "ListDevices":
		return s.devatteztInterface.ListDevices(ctx, VarlinkCall{call})

	case "Enroll":
		var in struct {
			Ekcert string `json:"ekcert"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.devatteztInterface.Enroll(ctx, VarlinkCall{call}, in.Ekcert)

	case "Remove":
		var in struct {
			Ekcert string `json:"ekcert"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.devatteztInterface.Remove(ctx, VarlinkCall{call}, in.Ekcert)

	default:
		return call.ReplyMethodNotFound(ctx, methodname)
	}
}

// Generated varlink interface name

func (s *VarlinkInterface) VarlinkGetName() string {
	return `dev.attezt`
}

// Generated varlink interface description

func (s *VarlinkInterface) VarlinkGetDescription() string {
	return `interface dev.attezt

type Device (
  ekcert: string
)

method GetDevice(ekcert: string) -> (device: Device)
method ListDevices() -> (devices: []Device)
method Enroll(ekcert: string) -> ()
method Remove(ekcert: string) -> ()
`
}

// Generated service interface

type VarlinkInterface struct {
	devatteztInterface
}

func VarlinkNew(m devatteztInterface) *VarlinkInterface {
	return &VarlinkInterface{m}
}
